# Generated by Django 5.1.7 on 2026-05-09 22:36

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('poi_type', models.CharField(choices=[('water_source', 'Water Source'), ('shelter', 'Shelter / Alpine Hut'), ('camping', 'Camping'), ('viewpoint', 'Viewpoint')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Point of Interest',
                'verbose_name_plural': 'Points of Interest',
            },
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('sac_scale', models.CharField(choices=[('hiking', 'T1 – Hiking'), ('mountain_hiking', 'T2 – Mountain Hiking'), ('demanding_mountain_hiking', 'T3 – Demanding Mountain Hiking'), ('alpine_hiking', 'T4 – Alpine Hiking'), ('demanding_alpine_hiking', 'T5 – Demanding Alpine Hiking'), ('difficult_alpine_hiking', 'T6 – Difficult Alpine Hiking')], default='hiking', max_length=50)),
                ('distance_km', models.FloatField(default=0.0)),
                ('elevation_gain_m', models.IntegerField(default=0)),
                ('surface', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sac_scale'], name='trails_trai_sac_sca_823e9d_idx'), models.Index(fields=['is_active'], name='trails_trai_is_acti_4d96f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrailNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('node_index', models.IntegerField()),
                ('elevation_m', models.FloatField(default=0.0)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='trails.trail')),
            ],
            options={
                'ordering': ['trail', 'node_index'],
            },
        ),
        migrations.CreateModel(
            name='TrailReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trail_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trails.trail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
