# Generated by Django 5.1.7 on 2026-05-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poi',
            options={'verbose_name': "Об'єкт інтересу (POI)", 'verbose_name_plural': "Об'єкти інтересу (POI)"},
        ),
        migrations.AlterModelOptions(
            name='trail',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршрути'},
        ),
        migrations.AlterModelOptions(
            name='trailnode',
            options={'ordering': ['trail', 'node_index'], 'verbose_name': 'Вузол маршруту', 'verbose_name_plural': 'Вузли маршруту'},
        ),
        migrations.AlterModelOptions(
            name='trailreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
        migrations.AddField(
            model_name='trail',
            name='colour',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='poi',
            name='poi_type',
            field=models.CharField(choices=[('water_source', 'Джерело води'), ('shelter', 'Притулок / Хата'), ('camping', 'Кемпінг'), ('viewpoint', 'Оглядовий майданчик')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trail',
            name='sac_scale',
            field=models.CharField(choices=[('hiking', 'T1 – Піший'), ('mountain_hiking', 'T2 – Гірський'), ('demanding_mountain_hiking', 'T3 – Вимогливий гірський'), ('alpine_hiking', 'T4 – Альпійський'), ('demanding_alpine_hiking', 'T5 – Вимогливий альпійський'), ('difficult_alpine_hiking', 'T6 – Складний альпійський')], default='hiking', max_length=50),
        ),
    ]
